INSERT INTO book VALUES(DEFAULT, 'Effective java', 'java', '2009-01-01');
INSERT INTO book VALUES(DEFAULT, 'Thinking in java', 'java', '2006-02-20');
INSERT INTO book VALUES(DEFAULT, 'Design Patterns', 'design', '1995-01-15');
INSERT INTO book VALUES(DEFAULT, 'Java Concurrency in Practice', 'java', '2006-05-19');
INSERT INTO book VALUES(DEFAULT, 'Patterns of Enterprise Application Architecture', 'architect', '2002-11-15');
INSERT INTO book VALUES(DEFAULT, 'Domain Driven Design', 'design', '2003-08-30');
INSERT INTO book VALUES(DEFAULT, 'Enterprise Integration Patterns', 'architect', '2003-10-20');
INSERT INTO book VALUES(DEFAULT, 'Refactoring', 'programming', '1999-07-08');
INSERT INTO book VALUES(DEFAULT, 'Clean Code', 'programming', '2008-01-01');
INSERT INTO book VALUES(DEFAULT, 'The Clean Coder', 'programming', '2011-05-26');